{
 "title": "dash-forum-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\",application=\"$application\"},pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "API uptime",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "timeseries",
   "description": "Estado das conexões com o database",
   "gridPos": { "h": 6, "w": 15, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",pool=\"HikariPool-1\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",pool=\"HikariPool-1\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",pool=\"HikariPool-1\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "Hora da Inicialização da API",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USERS LOGGED",
   "type": "stat",
   "description": "Usuários logados no último minuto",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "POOL DE CONEXÕES JDBC",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",pool=\"HikariPool-1\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "description": "Warnings e erros logados nos últimos 5m",
   "gridPos": { "h": 6, "w": 13, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "rate(logback_events_total{application=\"app-forum-api\",level=\"warn\"}[5m])",
     "legendFormat": "warn"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(logback_events_total{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",level=\"error\"}[5m]))",
     "legendFormat": "error2"
    },
    {
     "expr": "rate(logback_events_total{application=\"app-forum-api\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "AUTH ERRORS",
   "type": "stat",
   "description": "Erros de autenticação último minuto",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_error_total[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "DB CONNECTION TIMEOUT",
   "type": "stat",
   "description": "Conexões com o database em timeout",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",pool=\"HikariPool-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HEAP USED",
   "type": "gauge",
   "description": "Memória Heap Utilizada",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE",
   "type": "timeseries",
   "description": "Média de uso de CPU",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\"}",
     "legendFormat": "Load average [1m]"
    },
    {
     "expr": "system_cpu_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\"}",
     "legendFormat": "CPU core size"
    }
   ]
  },
  {
   "title": "NON-HEAP USED",
   "type": "gauge",
   "description": "Memória Non-heap utilizada",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU UTILIZATION",
   "type": "timeseries",
   "description": "Utilização de CPU",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\"}",
     "legendFormat": "System CPU usage"
    },
    {
     "expr": "process_cpu_usage{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\"}",
     "legendFormat": "Process CPU usage"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "TOTAL REQUESTS",
   "type": "stat",
   "description": "Número de requisições no último minuto",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Tempo de resposta no último minuto",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])/rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}}{{method}}{{status}}"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "description": "Latência Média por minuto",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75,sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25,sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Número de erros 500 no último minuto",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Taxa de erros nos últimos 5 minutos",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\", status=\"500\"}[5m]))/sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\", status=\"400\"}[5m]))/sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\", status=\"404\"}[5m]))/sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "NÚMERO DE REQUISIÇÕES POR ENDPOINT NO ÚLTIMO MINUTO",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri=\"/topicos\"}[1m]))",
     "legendFormat": "/topicos"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri=\"/topicos/{id}\"}[1m]))",
     "legendFormat": "/topicos/{id}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",uri=\"/auth\"}[1m]))",
     "legendFormat": "/auth"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "description": "Duração média de requisições no último minuto",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",status=\"200\",uri=\"/topicos\"}[1m])/rate(http_server_requests_seconds_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",status=\"200\",uri=\"/topicos\"}[1m])",
     "legendFormat": "{{uri}}{{method}}{{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",status=\"200\",uri=\"/topicos/{id}\"}[1m])/rate(http_server_requests_seconds_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",status=\"200\",uri=\"/topicos/{id}\"}[1m])",
     "legendFormat": "{{uri}}{{method}}{{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",status=\"200\",uri=\"/auth\"}[1m])/rate(http_server_requests_seconds_count{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",status=\"200\",uri=\"/auth\"}[1m])",
     "legendFormat": "{{uri}}{{method}}{{status}}"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "description": "Duração máxima de uma requisição",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"app-forum-api\",instance=\"app-forum-api:8080\",job=\"app-forum-api\",status=\"200\",uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}}{{method}}{{status}}"
    }
   ]
  }
 ]
}